export const macroSpecs=[{id:'DFII10',label:'10年期实际利率',unit:'%',threshold:25,deltaUnit:'bp',floor:-10,ceiling:30},{id:'BAMLH0A0HYM2',label:'高收益债信用利差',unit:'%',threshold:50,deltaUnit:'bp',floor:0,ceiling:100},{id:'DTWEXBGS',label:'广义美元指数',unit:'点',threshold:2,deltaUnit:'%',floor:1,ceiling:1000}];
export function parseMacro(html,spec,now=Date.now()){
 const observations=[];for(const m of html.matchAll(/#(\d{4}-\d{2}-\d{2})\|\s*(-?\d+(?:\.\d+)?)/g))observations.push({date:m[1],value:Number(m[2])});
 for(const m of html.matchAll(/<th[^>]*>\s*(\d{4}-\d{2}-\d{2})\s*<\/th>\s*<td[^>]*>\s*(-?\d+(?:\.\d+)?)\s*<\/td>/g))observations.push({date:m[1],value:Number(m[2])});
 const rows=[...new Map(observations.filter(r=>Number.isFinite(r.value)&&r.value>=spec.floor&&r.value<=spec.ceiling&&Number.isFinite(Date.parse(r.date))&&Date.parse(r.date+'T00:00:00Z')<=now).map(r=>[r.date,r])).values()].sort((a,b)=>a.date.localeCompare(b.date));
 if(!rows.length)throw Error('no observations');return rows;
}
export function summarizeMacro(inputs,now=Date.now()){
 const day=86400000;const valid=inputs.filter(x=>x.rows?.length&&now-Date.parse(x.rows.at(-1).date+'T00:00:00Z')<=7*day);const asOf=valid.length?valid.map(x=>x.rows.at(-1).date).sort()[0]:null;
 const cards=inputs.map(x=>{const spec=macroSpecs.find(s=>s.id===x.id);const base={...spec,url:'https://fred.stlouisfed.org/series/'+x.id,latestDate:x.rows?.at(-1)?.date};if(!x.rows?.length)return{...base,status:'missing'};if(!valid.includes(x))return{...base,status:'stale'};const rows=x.rows.filter(r=>r.date<=asOf);const last=rows.at(-1),previous=rows.at(-21);if(!last||!previous||last.date!==asOf)return{...base,status:'insufficient'};const change=spec.deltaUnit==='bp'?(last.value-previous.value)*100:(last.value/previous.value-1)*100;return{...base,status:'ok',date:last.date,previousDate:previous.date,value:last.value,change,direction:change>=spec.threshold?'rising':change<=-spec.threshold?'easing':'stable'};});
 const usable=cards.filter(c=>c.status==='ok'),rising=usable.filter(c=>c.direction==='rising').length,easing=usable.filter(c=>c.direction==='easing').length;return{asOf,cards,coverage:usable.length,headline:usable.length<3?'宏观证据不完整':rising>=2?'宏观压力上升':easing>=2?'宏观压力缓和':'宏观变化温和或分化',note:'按共同观察日期比较最近20个有效观测；实际利率+25bp、信用利差+50bp、美元+2%视为压力上升，反向同幅度视为缓和。至少两项同向且三项数据完整时生成方向标签。阈值为研究假设，未纳入买入信号或历史检验。'};
}
let macroCache;
export async function macro(){if(macroCache&&Date.now()-macroCache.time<900000)return Response.json(macroCache.data);const inputs=await Promise.all(macroSpecs.map(async spec=>{try{const r=await fetch('https://fred.stlouisfed.org/data/'+spec.id+'.txt',{signal:AbortSignal.timeout(12000),cf:{cacheTtl:900,cacheEverything:true}});if(!r.ok)throw Error();return{id:spec.id,rows:parseMacro(await r.text(),spec)};}catch{return{id:spec.id,rows:[]};}}));const data=summarizeMacro(inputs);if(data.coverage===3)macroCache={time:Date.now(),data};return Response.json(data,{headers:{'cache-control':'private, max-age=900'}});}
