import test from 'node:test';import assert from 'node:assert/strict';import {parseSOXXHoldings,calculateSOXXBreadth,getSOXXBreadth} from '../breadth.mjs';
const now=Date.parse('2026-10-09T23:00:00Z'),date='2026-10-08';
const holdings={date,symbols:Array.from({length:30},(_,i)=>'S'+i)};
const prices=(covered,above)=>holdings.symbols.slice(0,covered).map((symbol,i)=>({symbol,date,status:'ok',ma50:i<above?2:-2}));
test('full aligned 19 of 30 is 63.3%, while 17 of 30 is below the 60% gate',()=>{const a=calculateSOXXBreadth(holdings,prices(30,19),date,now),b=calculateSOXXBreadth(holdings,prices(30,17),date,now);assert.equal(a.status,'ok');assert.equal(a.covered,30);assert.ok(a.value>=60);assert.ok(b.value<60);assert.equal(a.checkedAt,new Date(now).toISOString());});
test('70% price coverage required; missing constituents are not zero or assumed positive',()=>{const a=calculateSOXXBreadth(holdings,prices(20,20),date,now);assert.equal(a.status,'missing');assert.equal(a.value,null);assert.equal(a.covered,20);const b=calculateSOXXBreadth(holdings,prices(21,14),date,now);assert.equal(b.status,'ok');assert.equal(b.value,100*14/21);});
test('no prices, stale/cached/review rows or different dates do not provide breadth',()=>{const mixed=prices(30,20).map((p,i)=>({...p,status:i<10?'ok':'cached'}));assert.equal(calculateSOXXBreadth(holdings,mixed,date,now).value,null);assert.equal(calculateSOXXBreadth(holdings,[],date,now).value,null);assert.equal(calculateSOXXBreadth({...holdings,date:'2026-10-07'},prices(30,20),date,now).value,null);assert.equal(calculateSOXXBreadth(holdings,prices(30,20).map(p=>({...p,date:'2026-10-07'})),date,now).value,null);});
test('fund CSV quotes parsed, cash excluded, truncated top list rejected',()=>{const csv='Fund Holdings as of,"Oct 08, 2026"\nTicker,Name,Asset Class\n'+holdings.symbols.map(s=>`"${s}","Company, Inc",Equity`).join('\n')+'\nUSD,Cash,Cash';const h=parseSOXXHoldings(csv);assert.deepEqual(h.symbols,holdings.symbols);assert.equal(h.date,date);assert.throws(()=>parseSOXXHoldings('Fund Holdings as of,"Oct 08, 2026"\nTicker,Name,Asset Class\nNVDA,Nvidia,Equity'));});
test('known valid watch prices reused; each remaining member fetched once',async()=>{let calls=0;const result=await getSOXXBreadth(null,date,prices(7,5),now,{holdingsLoader:async()=>holdings,priceLoader:async(symbol)=>{calls++;return{symbol,date,status:'ok',ma50:2};}});assert.equal(calls,23);assert.equal(result.covered,30);assert.equal(result.status,'ok');});
